# This workflow runs through the test suite

name: ci

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        id: pnpm-install

      - name: Install Dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Build Library
        run: pnpm run build

      - run: pnpx pkg-pr-new publish './packages/bootstrap-vue-next' './packages/nuxt' --template './templates/vite'

  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        id: pnpm-install

      - name: Install Dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Test Lint
        run: pnpm run test:lint:ci

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        id: pnpm-install

      - name: Install Dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Test Unit
        run: pnpm run test:unit:ci
